# Generated by Django 3.1.1 on 2020-09-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('l', 'COFFEE_MACHINE_LARGE'), ('s', 'COFFEE_MACHINE_SMALL'), ('e', 'ESPRESSO_MACHINE')], max_length=1)),
                ('water_line_compatible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('l', 'COFFEE_POD_LARGE'), ('s', 'COFFEE_POD_SMALL'), ('e', 'ESPRESSO_POD')], max_length=1)),
                ('coffee_flavor', models.CharField(choices=[('v', 'COFFEE_FLAVOR_VANILLA'), ('c', 'COFFEE_FLAVOR_CARAMEL'), ('p', 'COFFEE_FLAVOR_PSL'), ('m', 'COFFEE_FLAVOR_MOCHA'), ('h', 'COFFEE_FLAVOR_HAZELNUT')], max_length=1)),
                ('pack_size', models.CharField(choices=[('1', '1 dozen (12)'), ('3', '3 dozen (36)'), ('5', '5 dozen (60)'), ('7', '7 dozen (84)')], max_length=1)),
            ],
        ),
    ]
